
wbs_table <- tribble(~Level, ~ID,             ~Name,                                                    ~ParentID,
                     1L,	 "1.0",	          "Cerberus Autonomous Vehicles",	                        NA_character_,
                     2L,	 "1.1",	          "Family of Cerberus Autonomous Vehicle",	                "1.0",
                     3L,	 "1.1.1",	      "Cerberus Autonomous Vehicle (CAV)",	                    "1.1",
                     4L,	 "1.1.1.1",	      "CAV Integration, Assembly, Test, and Checkout",          "1.1.1",
                     4L,	 "1.1.1.2",	      "Hull/Frame/Body/Cab",	                                "1.1.1",
                     4L,	 "1.1.1.3",	      "System Survivability",	                                "1.1.1",
                     4L,	 "1.1.1.4",	      "Turret Assembly",	                                    "1.1.1",
                     4L,	 "1.1.1.5",	      "Suspension/Steering",	                                "1.1.1",
                     4L,	 "1.1.1.6",	      "Vehicle Electronics",	                                "1.1.1",
                     4L,	 "1.1.1.7",	      "Power Package/Drive Train",	                            "1.1.1",
                     5L,	 "1.1.1.7.1",	  "Power Package",	                                        "1.1.1.7",
                     6L,	 "1.1.1.7.1.1",	  "Dressed Engine",	                                        "1.1.1.7.1",
                     7L,	 "1.1.1.7.1.1.1", "Engine Block",	                                        "1.1.1.7.1.1",
                     7L,	 "1.1.1.7.1.1.2", "Turbocharger",	                                        "1.1.1.7.1.1",
                     7L,	 "1.1.1.7.1.1.3", "Other Dressed Engine",	                                "1.1.1.7.1.1",
                     6L,	 "1.1.1.7.1.2",	  "Transmission",	                                        "1.1.1.7.1",
                     5L,	 "1.1.1.7.2",	  "Drive Train",	                                        "1.1.1.7",
                     4L,	 "1.1.1.8",	      "Auxiliary Automotive",	                                "1.1.1",
                     4L,	 "1.1.1.9",	      "Fire Control",	                                        "1.1.1",
                     4L,	 "1.1.1.10",	  "Armament",	                                            "1.1.1",
                     4L,	 "1.1.1.11",	  "Automatic Ammunition Handling",	                        "1.1.1",
                     4L,	 "1.1.1.12",	  "Navigation and Remote Piloting Systems",	                "1.1.1",
                     4L,	 "1.1.1.13",	  "Special Equipment",	                                    "1.1.1",
                     4L,	 "1.1.1.14",	  "Communications",	                                        "1.1.1",
                     4L,	 "1.1.1.15",	  "CAV Software Release",	                                "1.1.1",
                     4L,	 "1.1.1.16",	  "Other CAV Subsystems",	                                "1.1.1",
                     3L,	 "1.1.2",	      "Variant 2 (Deprecated)",	                                "1.1",
                     3L,	 "1.1.3",	      "Equipment Kits",	                                        "1.1",
                     2L,	 "1.2",	          "Secondary Vehicle",	                                    "1.0",
                     2L,	 "1.3",	          "Systems Engineering",	                                "1.0",
                     3L,	 "1.3.1",	      "Software Systems Engineering",	                        "1.3",
                     3L,	 "1.3.2",	      "Integrated Logistics Support (ILS) Systems Engineering",	"1.3",
                     3L,	 "1.3.3",	      "Cybersecurity Systems Engineering",	                    "1.3",
                     3L,	 "1.3.4",	      "Core Systems Engineering",	                            "1.3",
                     3L,	 "1.3.5",	      "Other Systems Engineering 1...n (Specify)",	            "1.3",
                     2L,	 "1.4",	          "Program Management",	                                    "1.0",
                     3L,	 "1.4.1",	      "Software Program Management",	                        "1.4",
                     3L,	 "1.4.2",	      "Integrated Logistics Support (ILS) Program Management",	"1.4",
                     3L,	 "1.4.3",	      "Cybersecurity Management",	                            "1.4",
                     3L,	 "1.4.4",	      "Core Program Management",	                            "1.4",
                     3L,	 "1.4.5",	      "Other Program Management 1...n (Specify)",	            "1.4",
                     2L,	 "1.5",	          "System Test and Evaluation",	                            "1.0",
                     3L,	 "1.5.1",	      "Development Test and Evaluation",	                    "1.5",
                     3L,	 "1.5.2",	      "Operational Test and Evaluation",	                    "1.5",
                     3L,	 "1.5.3",	      "Cybersecurity Test and Evaluation",	                    "1.5",
                     3L,	 "1.5.4",	      "Mock-ups/System Integration Labs (SILs)",	            "1.5",
                     3L,	 "1.5.5",	      "Test and Evaluation Support",	                        "1.5",
                     3L,	 "1.5.6",	      "Test Facilities",	                                    "1.5",
                     2L,	 "1.6",	          "Training",	                                            "1.0",
                     3L,	 "1.6.1",	      "Equipment",	                                            "1.6",
                     4L,	 "1.6.1.1",	      "Operator Instructional Equipment",	                    "1.6.1",
                     4L,	 "1.6.1.2",	      "Maintainer Instructional Equipment",	                    "1.6.1",
                     3L,	 "1.6.2",	      "Services",	                                            "1.6",
                     4L,	 "1.6.2.1",	      "Operator Instructional Services",	                    "1.6.2",
                     4L,	 "1.6.2.2",	      "Maintainer Instructional Services",	                    "1.6.2",
                     3L,	 "1.6.3",	      "Facilities",	                                            "1.6",
                     3L,	 "1.6.4",	      "Training Software 1...n (Specify)",	                    "1.6",
                     2L,	 "1.7",	          "Data",	                                                "1.0",
                     3L,	 "1.7.1",	      "Data Deliverables 1...n (Specify)",	                    "1.7",
                     3L,	 "1.7.2",	      "Data Repository",	                                    "1.7",
                     3L,	 "1.7.3",	      "Data Rights 1...n (Specify)",	                        "1.7",
                     2L,	 "1.8",	          "Peculiar Support Equipment",	                            "1.0",
                     3L,	 "1.8.1",         "Test and Measurement Equipment",	                        "1.8",
                     3L,	 "1.8.2",         "Support and Handling Equipment",	                        "1.8",
                     2L,	 "1.9",	          "Common Support Equipment",	                            "1.0",
                     3L,	 "1.9.1",	      "Test and Measurement Equipment",	                        "1.9",
                     3L,	 "1.9.2",	      "Support and Handling Equipment",	                        "1.9",
                     2L,	 "1.10",	      "Operational/Site Activation by Site 1...n (Specify)",	"1.0",
                     3L,	 "1.10.1",	      "System Assembly, Installation, and Checkout on Site",	"1.10",
                     3L,	 "1.10.2",	      "Contractor Technical Support",	                        "1.10",
                     3L,	 "1.10.3",	      "Site Construction",	                                    "1.10",
                     3L,	 "1.10.4",	      "Site/Ship/Vehicle Conversion",	                        "1.10",
                     3L,	 "1.10.5",	      "Interim Contractor Support (ICS)",	                    "1.10",
                     2L,	 "1.11",	      "Contractor Logistics Support (CLS)",	                    "1.0",
                     2L,	 "1.12",	      "Industrial Facilities",	                                "1.0",
                     3L,	 "1.12.1",        "Construction/Conversion/Expansion",	                    "1.12",
                     3L,	 "1.12.2",        "Equipment Acquisition or Modernization",	                "1.12",
                     3L,	 "1.12.3",        "Maintenance (Industrial Facilities)",	                "1.12",
                     2L,	 "1.13",	      "Initial Spares and Repair Parts",	                    "1.0"
                     )
